import { Montserrat } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({ 
  subsets: ["latin"],
  // Montserrat comes in multiple weights - you can specify which ones you want to load
  weight: ["300", "400", "500", "600", "700"],
  // You can also specify italic styles if needed
  // style: ['normal', 'italic'],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>{children}</body>
    </html>
  );
}